{"name": "Проверка получения списка заказов с неправильным трек номером", "status": "passed", "description": "Негативный сценарий проверка получения списка заказов по трек номеру {negative_data}", "parameters": [{"name": "negative_data", "value": "[99999999, 404, 'Заказ не найден']"}], "start": 1757920957165, "stop": 1757920957774, "uuid": "d4dc8421-5715-41e0-ab6d-7e16bb4b091b", "historyId": "888b9e25823e37796b6ac4040b48741a", "testCaseId": "20c349e9cae5542ad8901f9d5aca8ab0", "fullName": "tests.test_get_order_by_number.TestGetOrderByNumber#test_get_order_by_number_negative_check_response", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_number"}, {"name": "subSuite", "value": "TestGetOrderByNumber"}, {"name": "host", "value": "RUMS01CW-F915A8"}, {"name": "thread", "value": "12672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_number"}], "titlePath": ["tests", "test_get_order_by_number.py", "TestGetOrderByNumber"]}